version: '3.1'

services:
  client:
    image: yandex/clickhouse-client
    container_name: clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity
      #clickhouse-client --host clickhouse-server
  server:
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    volumes:
      - ./data:/var/lib/clickhouse
    ports:
      - 8123:8123